name: Run build script on PR
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ragu/test'
    


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run workspace in /home/pxdata/ragu
        working-directory: /home/pxdata/ragu
        run: |
          # Add your build or script commands here
            sudo cp -r ${{ github.workspace }} /home/pxdata/ragu
            sudo chown -R pxuser:pxuser /home/pxdata/
