name: Run build script on PR
on:
  push:
    branches:
      - dev/IAM-2751

    

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (optional)'
        required: false
 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch user-specified tag or latest tag
        run: |
          set -e  # Exit on error
          
          # Navigate to the workspace
          cd ${{ github.workspace }}

          # Fetch all tags and branches
          git fetch --all --tags

          # Check if the user provided a tag
          USER_TAG=${{ github.event.inputs.tag }}  # Replace with your input mechanism
          echo "User-specified tag: $USER_TAG"

          if [ -n "$USER_TAG" ] && git rev-parse "$USER_TAG" >/dev/null 2>&1; then
            echo "User-specified tag exists: $USER_TAG"
            git checkout "$USER_TAG"
          else
            echo "User-specified tag not found or not provided. Fetching the latest tag."
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
            if [ -n "$LATEST_TAG" ]; then
              echo "Latest tag found: $LATEST_TAG"
              git checkout "$LATEST_TAG"
            else
              echo "No tags found. Fetching the latest code from the main branch."
              git checkout main
              git pull origin main
            fi
          fi
      - name: Set the cronjob
        run: |
          echo "*/5 * * * * pxdata /usr/bin/env bash /home/pxuser/your_script.sh" | sudo tee /etc/cron.d/your_cronjob

      - name: Run workspace in /home/pxdata/ragu
        run: |
          # Add your build or script commands here
            sudo  cp -r ${{ github.workspace }} /home/pxuser/
      - name: set the environment variables
        run: |
          sudo -u pxdata bash -c '
            export TID_ROOT_URL="https://stage.id.trimblecloud.com"
            export PxJobBucket="iam-dev-common-configs-uw2"
            export Environment="dev1"
            export IAM_AWS_REGION="us-west-2"
            export CENTRAL_TABLE="iam-central-dev1"
            export DAL="DYNAMODB"
            export DD_SERVICE="iam-users-px-data-operator"
            export IAM_ERROR_LINK="https://docs.trimblecloud.com/identity-and-access-management/content/reference/errors/api_errors/"
            export POWERTOOLS_SERVICE_NAME="iam-users-px-data-operator"
            export POWERTOOLS_LOG_LEVEL="INFO"
            export POWERTOOLS_METRICS_NAMESPACE="IAM"
            export TID_CLIENT_CERT="/iam/dev/iam_us_mtls_client_pem"
            export TID_CLIENT_KEY="/iam/dev/iam_us_mtls_client_key"
            export IDENTITY_SERVICE_URL="https://id-stg-us-int.stage.id.trimblecloud.com"
            export TID_API_KEY="/iam/dev/tid_us_pkey"
            export TID_API_TOKEN="/iam/dev/tid_us_token"
          '

         
