name: Run build script on PR
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ragu/test'
    


jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Run workspecr in /ragu
        run: |
          cd /home/pxdata/ragu
      - name: Checkout code
        uses: actions/checkout@v4
